# Generated by Django 3.2.4 on 2021-09-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField(unique=True)),
                ('to_age', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=-31.4135, null=True)),
                ('longitude', models.FloatField(default=-64.18105, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('spread_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.spreadsheet')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='dataMun.year')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.age')),
                ('center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.center')),
                ('diagnostic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.diagnostic')),
                ('sex', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.sex')),
                ('week', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.week')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataMun.zone'),
        ),
    ]
