# Generated by Django 3.2.4 on 2021-07-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField()),
                ('to_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnosticcases',
            name='age',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.age'),
        ),
        migrations.AlterField(
            model_name='diagnosticcases',
            name='sex',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.sex'),
        ),
    ]
