# Generated by Django 3.2.4 on 2021-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='tabla',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
