# Generated by Django 3.2.4 on 2021-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0002_diagnostic_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
