# Generated by Django 3.2.4 on 2021-06-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0002_alter_semana_tabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='semana',
            name='tabla',
        ),
    ]
