# Generated by Django 3.2.4 on 2021-10-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0003_alter_diagnostic_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
