# Generated by Django 3.2.4 on 2021-07-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0004_alter_year_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='from_age',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='to_age',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
