# Generated by Django 3.2.4 on 2021-10-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0004_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticcases',
            options={'verbose_name_plural': 'Diagnostic cases'},
        ),
    ]
