# Generated by Django 3.2.4 on 2021-06-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0008_auto_20210608_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='archivo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='dataMun.archivo'),
            preserve_default=True,
        ),
    ]
