# Generated by Django 3.2.4 on 2021-06-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataMun', '0009_semana_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataMun.archivo'),
        ),
    ]
